CALL cpp -I "C:\Users\cgomezco\Downloads\EHV_WWTP_WITH_CONTROL_CM_T1\blocks\WESTforKALLISTO - EHV10\Models" -DASM2dChemTemp -DINDEX_OF_FEED_LAYER=5 -DINDEX_OF_FEED_LAYER_BURGER=12 -DNR_OF_LAYERS=10 -DNR_OF_LAYERS_BURGER=20 -DNR_OF_LAYERS_BUT_ONE=9 -DNR_OF_LAYERS_PLUS_FOUR_BURGER=24 -DNR_OF_LAYERS_PLUS_ONE=11 -DNR_OF_LAYERS_PLUS_ONE_BURGER=21 -DNR_OF_LAYERS_PLUS_THREE_BURGER=23 -DNR_OF_LAYERS_PLUS_TWO_BURGER=22 "Eindhoven.Project.msl" "Eindhoven.Project.cpp.msl"
@IF %ERRORLEVEL% NEQ 0 GOTO End
CALL tmsl -ut "d" -i "..\..\blocks\WESTforKALLISTO - EHV10\External\External" "Eindhoven.Project.cpp.msl"
@IF %ERRORLEVEL% NEQ 0 GOTO End
CALL tbuild -S "..\..\blocks\WESTforKALLISTO - EHV10\External\External" -B "" _Eindhoven_
@IF %ERRORLEVEL% NEQ 0 GOTO End
:End
EXIT /B %ERRORLEVEL%
