CALL cpp -I "C:\Users\cgomezco\OneDrive - UGent\Documents\GitHub\AutomaticRecalibration\Recalibration_Eindhoven\blocks\MSL\Models" -DASM1Temp -DINDEX_OF_FEED_LAYER=5 -DINDEX_OF_FEED_LAYER_BURGER=25 -DNR_OF_LAYERS=10 -DNR_OF_LAYERS_BURGER=90 -DNR_OF_LAYERS_BUT_ONE=9 -DNR_OF_LAYERS_PLUS_FOUR_BURGER=94 -DNR_OF_LAYERS_PLUS_ONE=11 -DNR_OF_LAYERS_PLUS_ONE_BURGER=91 -DNR_OF_LAYERS_PLUS_THREE_BURGER=93 -DNR_OF_LAYERS_PLUS_TWO_BURGER=92 "BSM1_OL_ASM1.Project.msl" "BSM1_OL_ASM1.Project.cpp.msl"
@IF %ERRORLEVEL% NEQ 0 GOTO End
CALL tmsl -ut "d" -i "" "BSM1_OL_ASM1.Project.cpp.msl"
@IF %ERRORLEVEL% NEQ 0 GOTO End
CALL tbuild -S "" -B "" _BSM1_OL_ASM1_
@IF %ERRORLEVEL% NEQ 0 GOTO End
:End
EXIT /B %ERRORLEVEL%
